spring:
  application:
    name: newsys
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://112.150.97.37:3306/newsys-db
    username: root
    password: gksrnr1emd

logging:
  level:
    root: info
    com.growup: debug
